spotify:
  opts:
    clientId: 4eeb5550292f43b8b632d4981777b8bb
    clientSecret: nope
    redirectUri: http://localhost:1298/spotify/callback
  scopes:
    - playlist-read-private
    - playlist-modify-private

mysql:
  host: localhost
  database: wedding
  user: root
  password: password

sentry:
  enabled: false
  dsn: https://94e680aa0e3b4cec8fb1b78c735f5124@sentry.io/1270305
