spotify:
  clientId: 4eeb5550292f43b8b632d4981777b8bb
  secret: nope

mysql:
  host: localhost
  database: wedding
  user: root
  password: password

sentry:
  enabled: false
  dsn: https://94e680aa0e3b4cec8fb1b78c735f5124@sentry.io/1270305
