spotify:
  opts:
    clientId: 4eeb5550292f43b8b632d4981777b8bb
    clientSecret: nope
    redirectUri: http://localhost:1298/spotify/callback
  scopes:
    - playlist-read-private
    - playlist-modify-private
    - playlist-modify-public
  userId: 1173188384
  playlistId: 7ECCTRm37FPMkOMJ5nNvmr

mysql:
  host: localhost
  database: wedding
  user: root
  password: password

sentry:
  enabled: false
  dsn: https://94e680aa0e3b4cec8fb1b78c735f5124@sentry.io/1270305

photos:
  folders:
    GUEST: 1MCV5yLNzSXOm5Zfz_W2-Oj1sYxXIkQtG
    OFFICIAL: 1Vc-5MGhcHsnyBL4Jl685sCS-SKPtJZnA

weddingDate: '2019-07-27'
weddingStatusOverride: null
acceptPlaylistSubmissions: true
