sentry:
  enabled: true

spotify:
  opts:
    redirectUri: https://danniandoli.wedding/spotify/callback

photos:
  folders:
    GUEST:
    - 1MCV5yLNzSXOm5Zfz_W2-Oj1sYxXIkQtG
    OFFICIAL:
    - 1IFnpQSE-RMeBNr99-Ik3a7lbFCI-3CfQ
    - 133iPFJB37JZbSsB-O_KCOZtJRJAcWiu0
    - 1jLtk5x7f9rCZhxdzzVQUHX-vEo4fVULt
    - 1eoqbi2X0Vrr0GwfTGWSGdKt_aFgO5Wj1
    - 1sV9dR_xzz7llcDlg_KHZ938Tt2ZRPSws
    - 1Re16CQ6IZRAyA1auVQXJVzkC5YlD7x-Q
